name: Android debug APK
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.0-0.3.pre'
          channel: beta
          cache: true
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze
      - name: Flutter tests
        run: flutter test
      - name: Build debug APK
        run: flutter build apk --debug -t lib/main_libre.dart --flavor libre
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aves-media-enhanced-debug
          path: build/app/outputs/flutter-apk/app-libre-debug.apk
          if-no-files-found: error
